services:
  devhabit.api:
    image: ${DOCKER_REGISTRY-}devhabitapi
    build:
      context: .
      dockerfile: DevHabit.Api/Dockerfile
    ports:
      # - 5000:8080
      # - 5001:8081 
      - 5000:80
    environment:
      # Seq
      # - OTEL_EXPORTER_OTLP_ENDPOINT=http://devhabit.seq:5341/ingest/otlp  
      # - OTEL_EXPORTER_OTLP_PROTOCOL=http/protobuf
      # Aspire Dashboard
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://devhabit.aspire-dashboard:18889
      - OTEL_EXPORTER_OTLP_PROTOCOL=grpc


  devhabit.postgres:
    image: postgres:17.2
    environment:
      - POSTGRES_DB=devhabit 
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres123
    volumes:
      # - ./.containers/postgres_data:/var/lib/postgresql/data
      - ./.containers/database:/var/lib/postgresql/data
    ports:
      - 5433:5432

  devhabit.seq:
    image: datalust/seq:2024.3
    environment: 
      ACCEPT_EULA: "Y"
    volumes:
      - ./.containers/seq_data:/data
    ports: 
      - 8081:80
      - 5342:5342 

  devhabit.aspire-dashboard:
    image: mcr.microsoft.com/dotnet/aspire-dashboard:9.0 
    environment:
      DOTNET_DASHBOARD_UNSECURED_ALLOW_ANONYMOUS: true
    ports:
      - 18888:18888